prefix properties: <http://example.org/properties/>
prefix talk: <http://www.example.org/talks.rdfs>
select ?type where {
 {
  <http://example.org/talks/Doschoolskillcreativity> properties:related_talks ?y
  . BIND (?y as ?type)
} UNION
{
  ?x properties:related_talks <http://example.org/talks/Doschoolskillcreativity>
   . BIND (?x as ?type)
}
}
